# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-08 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default='media/None/no-img.jpg', upload_to='media/')),
            ],
        ),
    ]
