# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-09 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='model_pic',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
