# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-11 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200309_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, upload_to='test/')),
            ],
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='model_pic',
            field=models.ImageField(blank=True, upload_to='messy/'),
        ),
    ]
