# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200311_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, upload_to='clean/')),
            ],
        ),
        migrations.CreateModel(
            name='MessyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, upload_to='messy/')),
            ],
        ),
        migrations.CreateModel(
            name='NotcrModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, upload_to='notcr/')),
            ],
        ),
    ]
