# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-11 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cleanmodel_messymodel_notcrmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='model_pic',
            field=models.ImageField(blank=True, upload_to='misc/'),
        ),
    ]
