# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-18 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200311_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanTrainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, upload_to='train/clean/')),
            ],
        ),
        migrations.CreateModel(
            name='CleanValidationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, upload_to='validate/clean/')),
            ],
        ),
        migrations.CreateModel(
            name='CNNModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessyTrainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, upload_to='train/messy/')),
            ],
        ),
        migrations.CreateModel(
            name='MessyValidationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, upload_to='validate/messy/')),
            ],
        ),
        migrations.CreateModel(
            name='NotcrTrainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, upload_to='train/notcr/')),
            ],
        ),
        migrations.CreateModel(
            name='NotcrValidationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, upload_to='validate/notcr/')),
            ],
        ),
        migrations.DeleteModel(
            name='CleanModel',
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.DeleteModel(
            name='MessyModel',
        ),
        migrations.DeleteModel(
            name='NotcrModel',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
