# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-03 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200318_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnnmodel',
            name='model_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
