# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-03 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cnnmodel_model_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CleanValidationModel',
        ),
        migrations.DeleteModel(
            name='CNNModel',
        ),
        migrations.DeleteModel(
            name='MessyTrainModel',
        ),
        migrations.DeleteModel(
            name='MessyValidationModel',
        ),
        migrations.DeleteModel(
            name='NotcrTrainModel',
        ),
        migrations.DeleteModel(
            name='NotcrValidationModel',
        ),
    ]
