# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-24 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_messyvalidateimage_notcrvalidateimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='messyvalidateimage',
            name='image',
            field=models.ImageField(upload_to='validate/messy'),
        ),
        migrations.AlterField(
            model_name='notcrvalidateimage',
            name='image',
            field=models.ImageField(upload_to='validate/notcr'),
        ),
    ]
